import * as f from '../src/core/financials.js';
import { disconnect } from '../src/connection.js';
const log=(t,o)=>console.log(t,JSON.stringify(o));
const h=await f.history({symbol:'NASDAQ:AAPL',period:'annual',periods:5});
log('history annual ->', {ok:h.success,revenue:h.series.revenue,net_income:h.series.net_income,eps:h.series.eps_diluted});
const q=await f.history({symbol:'NASDAQ:AAPL',period:'quarterly',periods:4});
log('history quarterly revenue ->', q.series.revenue);
log('earnings ->', await f.earnings({symbol:'NASDAQ:AAPL'}));
log('dividends ->', await f.dividends({symbol:'NASDAQ:AAPL'}));
await disconnect();
